openapi: 3.0.1
info:
  title: 'Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /api/Images:
    post:
      tags:
        - Images
      operationId: UploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/Snippets:
    get:
      tags:
        - Snippets
      operationId: GetSnippets
      parameters:
        - name: searchTerm
          in: query
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SnippetDto'
    post:
      tags:
        - Snippets
      operationId: CreateSnippet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSnippetCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
  '/api/Snippets/{id}':
    get:
      tags:
        - Snippets
      operationId: GetSnippet
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnippetDto'
    put:
      tags:
        - Snippets
      operationId: UpdateSnippet
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSnippetCommand'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Snippets
      operationId: DeleteSnippet
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
components:
  schemas:
    CreateSnippetCommand:
      required:
        - code
        - language
        - title
      type: object
      properties:
        title:
          minLength: 1
          type: string
        description:
          type: string
          nullable: true
        language:
          minLength: 1
          type: string
        code:
          minLength: 1
          type: string
        docs:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
        imageUrls:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    SnippetDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        language:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        docs:
          type: string
          nullable: true
        isPinned:
          type: boolean
        tags:
          type: array
          items:
            type: string
          nullable: true
        imageUrls:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    UpdateSnippetCommand:
      required:
        - code
        - id
        - language
        - title
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          minLength: 1
          type: string
        description:
          type: string
          nullable: true
        language:
          minLength: 1
          type: string
        code:
          minLength: 1
          type: string
        docs:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
        imageUrls:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false